//
//  UserInteractor.swift
//  WhenToMock
//
//  Created by Raymond Law on 10/26/15.
//  Copyright (c) 2015 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol UserInteractorInput
{
  func fetchUser(request: UserRequest)
}

protocol UserInteractorOutput
{
  func presentUser(response: UserResponse)
}

class UserInteractor: UserInteractorInput
{
  var output: UserInteractorOutput!
  var worker = UserWorker()
  
  // MARK: Business logic
  
  func fetchUser(request: UserRequest)
  {
    let user = worker.fetchUser(request.userID)
    let response = UserResponse(user: user)
    output.presentUser(response)
  }
}
