//
//  UserConfigurator.swift
//  WhenToMock
//
//  Created by Raymond Law on 10/26/15.
//  Copyright (c) 2015 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension UserViewController: UserPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension UserInteractor: UserViewControllerOutput
{
}

extension UserPresenter: UserInteractorOutput
{
}

class UserConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: UserConfigurator
  {
    struct Static {
      static var instance: UserConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = UserConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: UserViewController)
  {
    let router = UserRouter()
    router.viewController = viewController
    
    let presenter = UserPresenter()
    presenter.output = viewController
    
    let interactor = UserInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
