//
//  UserPresenter.swift
//  WhenToMock
//
//  Created by Raymond Law on 10/26/15.
//  Copyright (c) 2015 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol UserPresenterInput
{
  func presentUser(response: UserResponse)
}

protocol UserPresenterOutput: class
{
  func displayUser(viewModel: UserViewModel)
}

class UserPresenter: UserPresenterInput
{
  weak var output: UserPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentUser(response: UserResponse)
  {
    let name = response.user.firstName + " " + response.user.lastName
    
    var phone = "Not available"
    if let cellPhone = response.user.cellPhone {
      phone = cellPhone
    } else if let homePhone = response.user.homePhone {
      phone = homePhone
    }
    
    let profilePhoto: UIImage
    if let image = response.user.profilePhoto {
      profilePhoto = image
    } else {
      profilePhoto = UIImage(named: "Default")!
    }
    
    let viewModel = UserViewModel(name: name, phone: phone, profilePhoto: profilePhoto)
    output.displayUser(viewModel)
  }
}
