//
//  UserModels.swift
//  WhenToMock
//
//  Created by Raymond Law on 10/26/15.
//  Copyright (c) 2015 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct UserRequest
{
  var userID: Int
}

struct UserResponse
{
  var user: User
}

struct UserViewModel
{
  var name: String
  var phone: String
  var profilePhoto: UIImage
}
